name: bbb-Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Packages
      run: sudo apt-get install squashfs-tools squashfuse

    - name: Configure
      run: |
        mkdir -p /home/runner/work/build
        cd /home/runner/work/build
        cmake /home/runner/work/C15/C15 -DBUILD_BBB=On -DBUILD_BBBB=Off -DBUILD_EPC=Off -DBUILD_AUDIOENGINE=Off -DBUILD_PLAYGROUND=Off -DBUILD_ONLINEHELP=Off -DBUILD_TESTING=Off

    - name: Build BBB
      run: |
        make -C /home/runner/work/build bbb-rootfs
        rm /home/runner/work/build/build-tools/bbb/rootfs.tar.gz

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: bbb-build
        path: /home/runner/work/build/build-tools/bbb/nonlinux/output/images
