name: epc-Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        mkdir -p /home/runner/work/build
        cd /home/runner/work/build
        cmake -DBUILD_EPC=On -DBUILD_AUDIOENGINE=Off -DBUILD_BBB=Off -DBUILD_BBBB=Off -DBUILD_PLAYGROUND=Off -DBUILD_ONLINEHELP=Off -DBUILD_TEXT2SOLED=Off -DBUILD_TESTING=Off /home/runner/work/C15/C15

    - name: Build update
      run: |
        cd /home/runner/work/build
        make epc-create-update
        mkdir -p /home/runner/work/build/build-tools/epc/final-image
        cp /home/runner/work/build/build-tools/epc/update.tar /home/runner/work/build/build-tools/epc/final-image/

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: epc-build
        path: /home/runner/work/build/build-tools/epc/final-image

